# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

before_install:
- sudo apt-get install libv8-dev
- sudo apt-get install libhdf5-dev libhdf5-serial-dev libgdal-dev libgdal1-dev libproj-dev

r_binary_packages:
- rgdal
- soilDB
- sp
- raster
- RCurl

r_github_packages:
- bocinsky/FedData

after_success:
- Rscript -e 'install.packages("SSOAP", repos="http://www.omegahat.org/R", type="source")'
- Rscript -e 'install.packages("XMLSchema", repos="http://www.omegahat.org/R", type="source")'

notifications:
email:
on_success: change
on_failure: change
