# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
os: osx
osx_image: xcode8

before_install:
  - brew update
  - brew upgrade
  - brew install gdal
  
language: r
cache: packages
r:
  - oldrel
  - release
  - devel