# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

sudo: required

before_install:
- sudo apt-get install aptitude
- sudo aptitude install libgdal-dev libproj-dev --assume-yes

#r_binary_packages:
#- rgdal
#- sp
#- raster

#r_github_packages:
#- bocinsky/FedData

# after_success:


notifications:
email:
on_success: change
on_failure: change
