# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
sudo: required
dist: trusty

before_install:
  - sudo apt-get install -y libproj-dev libcurl4-gnutls-dev libdap-dev libgdal-dev libgdal1h libhdf5-dev libhdf5-serial-dev libgdal-dev libgdal1-dev
  
language: r
cache: packages
r:
  - oldrel
  - release
  - devel