# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

r:
  - oldrel
  - release
  - devel

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y aptitude
  - sudo aptitude install libgdal-dev libproj-dev --assume-yes

r_binary_packages:
  - rgdal