# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

global:
- _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
- sudo apt-get install aptitude
- sudo aptitude install libgdal1-dev libproj-dev --assume-yes
- Rscript -e 'install.packages("SSOAP", repos="http://www.omegahat.org/R", type="source")'
- Rscript -e 'install.packages("XMLSchema", repos="http://www.omegahat.org/R", type="source")'

r_binary_packages:
- rgdal
- soilDB
- sp
- raster
- RCurl

r_github_packages:
- bocinsky/FedData

# after_success:


notifications:
email:
on_success: change
on_failure: change
