# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
sudo: false

before_install:
  - apt-get update -qq
  - apt-get install -y aptitude
  - aptitude install -y libproj-dev libgdal-dev
  
language: r
cache: packages
r:
  - oldrel
  - release
  - devel