language: r
sudo: required
cache: packages

r:
  - oldrel
  - release
  - devel

#warnings_are_errors: false
before_install:
  - export CURWD=`pwd`
  - sudo add-apt-repository ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo ldconfig
  - sudo ldconfig
  - cd $CURWD

apt_packages:
  - libssl-dev
  - libcurl4-openssl-dev
  - netcdf-bin
  - libnetcdf-dev
  - gdal-bin
  - libgdal-dev
  
r_packages:
  - roxygen2
  - survival

notifications:
  email:
    on_success: change
    on_failure: change