language: r
sudo: required
cache: packages

r:
  - oldrel
  - release
  - devel

#warnings_are_errors: false

apt_packages:
  - libproj-dev
  - netcdf-bin
  - libnetcdf-dev
  - gdal-bin
  - libgdal-dev
  
r_packages:
  - roxygen2
  - survival

notifications:
  email:
    on_success: change
    on_failure: change